-- Write SQL queries to perform the following tasks using the Sakila database:
USE sakila;

-- 1. List the number of films per category.

SELECT c.name, COUNT(f.film_id) AS number_of_films
FROM film_category as f
JOIN category as c
ON f.category_id = c.category_id
GROUP BY c.category_id;

-- 2. Retrieve the store ID, city, and country for each store.

SELECT s.store_id, c.city, co.country
FROM store AS s
LEFT JOIN address AS a
ON s.address_id = a.address_id
JOIN city AS c
ON a.city_id = c.city_id
JOIN country AS co
ON c.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.

SELECT s.store_id, SUM(p.amount) AS total_revenue
FROM store AS s
LEFT JOIN staff AS st
ON s.store_id = st.store_id
JOIN payment AS p
ON st.staff_id = p.staff_id
GROUP BY s.store_id;

-- 4. Determine the average running time of films for each category.

SELECT category_id, ROUND(AVG(f.length),2) AS average_length
FROM film_category AS c
JOIN film AS f
ON c.film_id = f.film_id
GROUP BY category_id
ORDER BY average_length DESC;

-- Bonus:
-- 5. Identify the film categories with the longest average running time.

WITH avg_length AS (SELECT ca.name, c.category_id, AVG(f.length) AS average_length
					FROM film_category AS c
					JOIN film AS f
					ON c.film_id = f.film_id
                    JOIN category as ca
                    ON c.category_id = ca.category_id
					GROUP BY category_id)
SELECT name, ROUND(average_length, 0) AS maximum_length
FROM avg_length
WHERE average_length = (SELECT MAX(average_length) FROM avg_length);

-- 6. Determine if "Academy Dinosaur" can be rented from Store 1.

SELECT f.title, i.store_id, COUNT(i.store_id) AS number_of_available_films
FROM film AS f
JOIN inventory AS i
ON f.film_id = i.film_id
GROUP BY f.title, i.store_id
HAVING f.title LIKE 'ACADEMY DINOSAUR' AND i.store_id = 1;

-- 7. Provide a list of all distinct film titles, along with their availability status in the inventory. Include a column indicating whether each title is 'Available' or 'NOT available.' 
-- Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."

SELECT 	f.title,
		COUNT(i.inventory_id) AS number_of_available_films,
		IFNULL(CASE 
				WHEN COUNT(i.inventory_id) != 0 THEN 'In inventory' 
                ELSE 'Not in inventory' END, 'Not in inventory') AS inventory_availability
FROM film AS f
LEFT JOIN inventory AS i
ON f.film_id = i.film_id
GROUP BY f.title;

-- Tip 1: This lab involves joins with multiple tables, which can be challenging. Take your time and follow the steps we discussed in class:

-- Make sure you understand the relationships between the tables in the database. This will help you determine which tables to join and which columns to use in your joins.
-- Identify a common column for both tables to use in the ON section of the join. If there isn't a common column, you may need to add another table with a common column.
-- Decide which table you want to use as the left table (immediately after FROM) and which will be the right table (immediately after JOIN).
-- Determine which table you want to include all records from. This will help you decide which type of JOIN to use. If you want all records from the first table, use a LEFT JOIN. If you want all records from the second table, use a RIGHT JOIN. If you want records from both tables only where there is a match, use an INNER JOIN.
-- Use table aliases to make your queries easier to read and understand. This is especially important when working with multiple tables.
-- Write the query
-- Tip 2: Break down the problem into smaller, more manageable parts. For example, you might start by writing a query to retrieve data from just two tables before adding additional tables to the join. Test your queries as you go, and check the output carefully to make sure it matches what you expect. This process takes time, so be patient and go step by step to build your query incrementally.